// var columns = [
//     {title: "Job ID", field: "job_id", hidden: true},
//     {title: "Date", field: "date"},
//     {title: "Code", field: "job_code"},
//     {title: "Category", field: "job_category"},
//     {title: "Title", field: "job_title"},
//     {title: "Location", field: "job_location"},
//     {title: "Positions", field: "job_positions"},
//     {title: "Job Description 1", field: "job_descriptionA"},
//     {title: "Job Description 2", field: "job_descriptionB"},
//     {title: "Job Description 3", field: "job_descriptionC"},
//     {title: "Job Description 4", field: "job_descriptionD"},
//     {title: "Job Description 5", field: "job_descriptionE"},
//     {title: "Job Description 6", field: "job_descriptionF"},
//     {title: "Job Description 7", field: "job_descriptionG"},
//     {title: "Job Description 8", field: "job_descriptionH"},
//     {title: "Job Qualification 1", field: "job_qualificationA"},
//     {title: "Job Qualification 2", field: "job_qualificationB"},
//     {title: "Job Qualification 3", field: "job_qualificationC"},
//     {title: "Job Qualification 4", field: "job_qualificationD"},
//     {title: "Job Qualification 5", field: "job_qualificationE"},
//     {title: "Job Experience", field: "job_experience"},
//     ]